# Generated by Django 3.2 on 2021-05-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20210508_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('describtion', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
