# Generated by Django 3.2 on 2021-05-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210510_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_discount',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_slider',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_two_blocks',
            field=models.BooleanField(null=True),
        ),
    ]
