# Generated by Django 3.2 on 2021-05-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20210522_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='parent',
        ),
        migrations.AddField(
            model_name='tag',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='_item_tag_children_+', to='item.Tag'),
        ),
    ]
